# Generated by Django 5.0.2 on 2024-02-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
