# Generated by Django 5.0.2 on 2024-02-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_tag_options_alter_tag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_tags', to='posts.tag', verbose_name='Tag'),
        ),
    ]
