# Generated by Django 5.0.2 on 2024-02-27 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_answer', to='posts.replycomment', verbose_name='Report answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_creator', to=settings.AUTH_USER_MODEL, verbose_name='Report author')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_comment', to='posts.comment', verbose_name='Report comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_post', to='posts.post', verbose_name='Report post')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Report recipient')),
            ],
        ),
    ]
