# Generated by Django 5.0.2 on 2024-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_first_name_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='count_of_followers',
            field=models.IntegerField(default=0, verbose_name='count_of_followers'),
        ),
    ]
