# Generated by Django 5.0.2 on 2024-02-24 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_pictures/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG'])], verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_pictures/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG'])], verbose_name='Picture'),
        ),
    ]
