# Generated by Django 5.0.2 on 2024-02-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_profile_banner_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='frends', to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Age'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_request_creator', to=settings.AUTH_USER_MODEL, verbose_name='Request author')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_request_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Request recipient')),
            ],
        ),
    ]
