# Generated by Django 5.0.2 on 2024-02-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_friendrequest_status_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
